flowchart TD
    subgraph Components["Ideas To Life Cas System Components"]
        comp_flowrunner["FlowRunner<br/><i>[src/cas_runner/runner.py]</i>"]
        comp_knowledgeprovider["KnowledgeProvider<br/><i>[src/cas_runner/io.py]</i>"]
        comp_localknowledgeprovider["LocalKnowledgeProvider<br/><i>[src/cas_runner/io.py]</i>"]
        comp_targetprojectcontext["TargetProjectContext<br/><i>[src/cas_runner/io.py]</i>"]
        comp_resolve_target_project_context["resolve_target_project_context<br/><i>[src/cas_runner/io.py]</i>"]
        comp_bootstrap["bootstrap<br/><i>[src/cas_runner/bootstrap.py]</i>"]
        comp_init_workspace["init_workspace<br/><i>[src/cas_runner/bootstrap.py]</i>"]
        comp_safe_mkdir["safe_mkdir<br/><i>[src/cas_runner/io.py]</i>"]
        comp_get_default_base["get_default_base<br/><i>[src/cas_runner/io.py]</i>"]
        comp_get_workspace_name["get_workspace_name<br/><i>[src/cas_runner/io.py]</i>"]
        comp_get_provider["get_provider<br/><i>[src/cas_runner/io.py]</i>"]
        comp_get_workspace_root["get_workspace_root<br/><i>[src/cas_runner/io.py]</i>"]
        comp_get_telemetry_root["get_telemetry_root<br/><i>[src/cas_runner/io.py]</i>"]
        comp_load_architecture_state["load_architecture_state<br/><i>[src/cas_runner/io.py]</i>"]
        comp_load_baseline_assessment["load_baseline_assessment<br/><i>[src/cas_runner/io.py]</i>"]
        comp_load_conversation["load_conversation<br/><i>[src/cas_runner/io.py]</i>"]
        comp_load_foundational_assets["load_foundational_assets<br/><i>[src/cas_runner/io.py]</i>"]
        comp_portal_preprocessor["PortalPreprocessor<br/><i>[src/cas_runner/portal_preprocessor.py]</i>"]
    end
    comp_flowrunner --> comp_localknowledgeprovider
    comp_flowrunner --> comp_targetprojectcontext
    comp_localknowledgeprovider --> comp_knowledgeprovider
    comp_portal_preprocessor --> comp_safe_mkdir
