flowchart LR
    subgraph flow:workflow:github:cas_sdd_validation["CAS SDD Validation"]
        direction LR
            flow:workflow:github:cas_sdd_validation_s0["1. Checkout Code"]
            flow:workflow:github:cas_sdd_validation_s1["2. Validate Specification Presence"]
            flow:workflow:github:cas_sdd_validation_s0 --> flow:workflow:github:cas_sdd_validation_s1
    end
