flowchart LR
    subgraph sg_workflow["Workflow"]
        flow_workflow_github_cas_sdd_validation["CAS SDD Validation"]
        flow_workflow_github_cas_sdd_validation -.-> comp_ea4all_automation_main_comp["ea4all-automation-main-comp"]
    end