flowchart LR
    subgraph sg_agent["Agent"]
        flow_agent_evidence_sufficiency_execution_workflow["Evidence Sufficiency Workflow"]
        flow_agent_evidence_sufficiency_execution_workflow -.-> comp_comp_skill_evidence_sufficiency["comp-skill-evidence-sufficiency"]
        flow_agent_evidence_sufficiency_execution_workflow -.-> comp_comp_evidencesufficiencyvalidator["comp-evidencesufficiencyvalidator"]
    end
    subgraph sg_governance["Governance"]
        flow_governance_speckit_checklist_execution_workflow["Speckit Checklist Workflow"]
        flow_governance_speckit_git_remote_execution_workflow["Speckit Git Remote Workflow"]
        flow_governance_speckit_git_validate_execution_workflow["Speckit Git Validate Workflow"]
        flow_governance_speckit_assess_define_execution_workflow["Speckit Assess Define Workflow"]
        flow_governance_speckit_assess_shape_execution_workflow["Speckit Assess Shape Workflow"]
        flow_governance_speckit_constitution_execution_workflow["Speckit Constitution Workflow"]
        flow_governance_speckit_implement_execution_workflow["Speckit Implement Workflow"]
        flow_governance_speckit_converge_execution_workflow["Speckit Converge Workflow"]
        flow_governance_speckit_assess_research_execution_workflow["Speckit Assess Research Workflow"]
        flow_governance_speckit_taskstoissues_execution_workflow["Speckit Taskstoissues Workflow"]
        flow_governance_speckit_assess_decide_execution_workflow["Speckit Assess Decide Workflow"]
        flow_governance_speckit_clarify_execution_workflow["Speckit Clarify Workflow"]
        flow_governance_speckit_plan_execution_workflow["Speckit Plan Workflow"]
        flow_governance_speckit_git_feature_execution_workflow["Speckit Git Feature Workflow"]
        flow_governance_speckit_analyze_execution_workflow["Speckit Analyze Workflow"]
        flow_governance_speckit_git_commit_execution_workflow["Speckit Git Commit Workflow"]
        flow_governance_speckit_specify_execution_workflow["Speckit Specify Workflow"]
        flow_governance_speckit_assess_intake_execution_workflow["Speckit Assess Intake Workflow"]
        flow_governance_speckit_tasks_execution_workflow["Speckit Tasks Workflow"]
        flow_governance_cas_add_or_modify_feature_execution_workflow["Cas Add Or Modify Feature Workflow"]
        flow_governance_cas_refactor_module_execution_workflow["Cas Refactor Module Workflow"]
    end
    subgraph sg_workflow["Workflow"]
        flow_workflow_github_cas_sdd_validation["CAS SDD Validation"]
    end